### ISSUE TITLE
server crashes when word is not found

### ISSUE THREAD

**Issue by peterbsmyth** [kseniya292/vocabulary-app-server#2]
server output: 
```
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Request.callback [as _callback] (/Users/Peter/code/community/vocabulary-app-server/api/controllers/DefinitionController.js:29:33)
    at Request.self.callback (/Users/Peter/code/community/vocabulary-app-server/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/Peter/code/community/vocabulary-app-server/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/Peter/code/community/vocabulary-app-server/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by kseniya292** [comment]
Yes, I need to add a To Do to display different messaged based on the server error response.
